version: "3.9"

services:
  web:
    build: .
    command: gunicorn educore.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    container_name: django_project

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: educore_db
      POSTGRES_USER: educore_user
      POSTGRES_PASSWORD: educore_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    container_name: educore_container_db

  redis:
    image: redis:latest
    container_name: redis_broker
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A educore worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
    container_name: celery_worker

  celery-beat:
    build: .
    command: celery -A educore beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
    container_name: celery_beat

volumes:
  postgres_data:
  static_volume:
